# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timesync.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'timesync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etimesync.proto\x12\x08timesync\"\r\n\x0bTimeRequest\"$\n\x0cTimeResponse\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\xa0\x01\n\x0fTimeSyncService\x12\x41\n\x10RequestTimestamp\x12\x15.timesync.TimeRequest\x1a\x16.timesync.TimeResponse\x12J\n\x0b\x43heckHealth\x12\x1c.timesync.HealthCheckRequest\x1a\x1d.timesync.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timesync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEREQUEST']._serialized_start=28
  _globals['_TIMEREQUEST']._serialized_end=41
  _globals['_TIMERESPONSE']._serialized_start=43
  _globals['_TIMERESPONSE']._serialized_end=79
  _globals['_HEALTHCHECKREQUEST']._serialized_start=81
  _globals['_HEALTHCHECKREQUEST']._serialized_end=101
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=103
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=141
  _globals['_TIMESYNCSERVICE']._serialized_start=144
  _globals['_TIMESYNCSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
