# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/time/proto/timesync.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'core/time/proto/timesync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ore/time/proto/timesync.proto\x12\x08timesync\"\r\n\x0bTimeRequest\"$\n\x0cTimeResponse\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\"\x14\n\x12HealthCheckRequest\"s\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x03\x12\x15\n\rrequest_count\x18\x03 \x01(\x03\x12\x1c\n\x14\x61vg_response_time_ms\x18\x04 \x01(\x01\x32\xa0\x01\n\x0fTimeSyncService\x12\x41\n\x10RequestTimestamp\x12\x15.timesync.TimeRequest\x1a\x16.timesync.TimeResponse\x12J\n\x0b\x43heckHealth\x12\x1c.timesync.HealthCheckRequest\x1a\x1d.timesync.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.time.proto.timesync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEREQUEST']._serialized_start=44
  _globals['_TIMEREQUEST']._serialized_end=57
  _globals['_TIMERESPONSE']._serialized_start=59
  _globals['_TIMERESPONSE']._serialized_end=95
  _globals['_HEALTHCHECKREQUEST']._serialized_start=97
  _globals['_HEALTHCHECKREQUEST']._serialized_end=117
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=119
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=234
  _globals['_TIMESYNCSERVICE']._serialized_start=237
  _globals['_TIMESYNCSERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
