# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.time.server import timesync_pb2 as core_dot_time_dot_proto_dot_timesync__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in core/time/proto/timesync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimeSyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTimestamp = channel.unary_unary(
                '/timesync.TimeSyncService/RequestTimestamp',
                request_serializer=core_dot_time_dot_proto_dot_timesync__pb2.TimeRequest.SerializeToString,
                response_deserializer=core_dot_time_dot_proto_dot_timesync__pb2.TimeResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/timesync.TimeSyncService/CheckHealth',
                request_serializer=core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TimeSyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTimestamp,
                    request_deserializer=core_dot_time_dot_proto_dot_timesync__pb2.TimeRequest.FromString,
                    response_serializer=core_dot_time_dot_proto_dot_timesync__pb2.TimeResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckRequest.FromString,
                    response_serializer=core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timesync.TimeSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('timesync.TimeSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimeSyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timesync.TimeSyncService/RequestTimestamp',
            core_dot_time_dot_proto_dot_timesync__pb2.TimeRequest.SerializeToString,
            core_dot_time_dot_proto_dot_timesync__pb2.TimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timesync.TimeSyncService/CheckHealth',
            core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckRequest.SerializeToString,
            core_dot_time_dot_proto_dot_timesync__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
